name: Build and Push Docker

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1
        with:
          submodules: recursive
      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a # v2
        with:
          push: true # Will only build if this is not here
          tags: |
            ghcr.io/${{ github.repository }}:latest
      - name: Build and Push WWW Docker Image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a # v2
        with:
          push: true
          file: Dockerfile.www
          tags: |
            ghcr.io/${{ github.repository }}-web:latest
