name: Build and Push Docker

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1
        with:
          submodules: recursive
      - name: Login to GitHub Container Registry
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          push: true # Will only build if this is not here
          tags: |
            ghcr.io/${{ github.repository }}:latest
      - name: Build and Push WWW Docker Image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          push: true
          file: Dockerfile.www
          tags: |
            ghcr.io/${{ github.repository }}-web:latest
